// Contract configuration and ABIs
export {
  CONTRACT_ADDRESSES,
  POOL_FACTORY_ABI,
  POOL_ABI,
  BADGE_ABI,
  LOTTERY_MANAGER_ABI,
  YIELD_MANAGER_ABI,
  REWARD_NFT_ABI,
  getContractAddress,
} from './config'

// Contract types
export type {
  PoolState,
  PoolInfo,
  PoolMember,
  PoolDetails,
  LotteryRound,
  BadgeType,
  BadgeMetadata,
  YieldInfo,
  CreatePoolParams,
  JoinPoolParams,
  UsePoolFactoryReturn,
  UsePoolReturn,
  UseBadgeReturn,
  UseLotteryReturn,
  UseYieldManagerReturn,
  PoolCreatedEvent,
  MemberJoinedEvent,
  PoolStateChangedEvent,
  LotteryDrawnEvent,
  YieldUpdatedEvent,
  BadgeMintedEvent,
} from './types'

// Contract utilities
export {
  formatPoolState,
  getPoolStateColor,
  isPoolJoinable,
  isPoolActive,
  isPoolCompleted,
  formatBadgeType,
  getBadgeIcon,
  getBadgeDescription,
  formatTimeRemaining,
  isPoolExpired,
  calculateAPY,
  calculateProjectedYield,
  shortenAddress,
  isValidAddress,
  formatAmount,
  parseAmount,
  calculatePercentage,
  formatPercentage,
  parseContractError,
  validatePoolCreation,
  POOL_CONSTANTS,
} from './utils'
